#ifndef REACHY_REFERENCE_SCENARIO_GENERATED_H
#define REACHY_REFERENCE_SCENARIO_GENERATED_H

#include <stdint.h>

/* Generated by scripts/generate_reachy_reference_header.py. */
#define REACHY_REFERENCE_SCENARIO_SCHEMA_VERSION 1U
#define REACHY_REFERENCE_TOTAL_STEPS UINT64_C(900)
#define REACHY_REFERENCE_ACTUATOR_COUNT 9U
#define REACHY_REFERENCE_BODY_COUNT 17U
#define REACHY_REFERENCE_PHASE_COUNT 4U
#define REACHY_REFERENCE_CHECKPOINT_COUNT 10U
#define REACHY_REFERENCE_EXPECTED_NQ 37U
#define REACHY_REFERENCE_EXPECTED_NV 30U

typedef struct ReachyReferencePhase {
    uint64_t start_step;
    const char* name;
    double targets[REACHY_REFERENCE_ACTUATOR_COUNT];
} ReachyReferencePhase;

static const char REACHY_REFERENCE_SCENARIO_ID[] = "rma042_representative_motion_v1";
static const char REACHY_REFERENCE_SCENARIO_SHA256[] = "534b92d7aa09247dffb4f101be6d000764bb28d46b533fafa0ed30490c74b776";
static const char REACHY_REFERENCE_MODEL_SHA256[] = "efd7e49d4288e5ef53945771a1f116584aa2c8b89721b725d5d77da9f0fcbf46";
static const char REACHY_REFERENCE_MUJOCO_VERSION[] = "3.9.0";
static const double REACHY_REFERENCE_TIMESTEP_SECONDS = 0.002;
static const double REACHY_REFERENCE_MAXIMUM_EQUALITY_RESIDUAL = 0.001;

static const char* const REACHY_REFERENCE_ACTUATOR_NAMES[REACHY_REFERENCE_ACTUATOR_COUNT] = {
    "yaw_body",
    "stewart_1",
    "stewart_2",
    "stewart_3",
    "stewart_4",
    "stewart_5",
    "stewart_6",
    "right_antenna",
    "left_antenna",
};

static const char* const REACHY_REFERENCE_BODY_NAMES[REACHY_REFERENCE_BODY_COUNT] = {
    "body_foot_3dprint",
    "body_down_3dprint",
    "dc15_a01_horn_dummy",
    "stewart_link_rod",
    "dc15_a01_horn_dummy_2",
    "stewart_link_rod_2",
    "dc15_a01_horn_dummy_3",
    "stewart_link_rod_3",
    "dc15_a01_horn_dummy_4",
    "stewart_link_rod_4",
    "dc15_a01_horn_dummy_5",
    "stewart_link_rod_5",
    "dc15_a01_horn_dummy_6",
    "stewart_link_rod_6",
    "xl_330",
    "dc15_a01_horn_dummy_7",
    "dc15_a01_horn_dummy_8",
};

static const uint64_t REACHY_REFERENCE_CHECKPOINT_STEPS[REACHY_REFERENCE_CHECKPOINT_COUNT] = {
    UINT64_C(0),
    UINT64_C(1),
    UINT64_C(50),
    UINT64_C(100),
    UINT64_C(150),
    UINT64_C(350),
    UINT64_C(400),
    UINT64_C(600),
    UINT64_C(700),
    UINT64_C(900),
};

static const ReachyReferencePhase REACHY_REFERENCE_PHASES[REACHY_REFERENCE_PHASE_COUNT] = {
    {UINT64_C(0), "neutral_settle", {0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {UINT64_C(100), "pose_a", {0.17999999999999999, 0.25, -0.20000000000000001, 0.17999999999999999, -0.14999999999999999, 0.22, -0.17000000000000001, 0.29999999999999999, -0.25}},
    {UINT64_C(350), "pose_b", {-0.12, -0.20000000000000001, 0.17999999999999999, -0.14999999999999999, 0.20000000000000001, -0.17999999999999999, 0.16, -0.20000000000000001, 0.28000000000000003}},
    {UINT64_C(600), "return_neutral", {0, 0, 0, 0, 0, 0, 0, 0, 0}},
};

static const uint32_t REACHY_REFERENCE_EXPECTED_BODY_COUNT = 19U;
static const uint32_t REACHY_REFERENCE_EXPECTED_JOINT_COUNT = 16U;
static const uint32_t REACHY_REFERENCE_EXPECTED_ACTUATOR_COUNT = 9U;
static const uint32_t REACHY_REFERENCE_EXPECTED_EQUALITY_COUNT = 5U;
static const uint32_t REACHY_REFERENCE_EXPECTED_SITE_COUNT = 13U;
static const uint32_t REACHY_REFERENCE_EXPECTED_CAMERA_COUNT = 2U;

#endif
