#ifndef REACHY_STABILITY_PROFILE_GENERATED_H
#define REACHY_STABILITY_PROFILE_GENERATED_H

#include <stdint.h>

/* Generated by scripts/generate_reachy_stability_header.py. */
#define REACHY_STABILITY_PROFILE_SCHEMA_VERSION 1U
#define REACHY_STABILITY_ACTUATOR_COUNT 9U
#define REACHY_STABILITY_PHASE_COUNT 20U
#define REACHY_STABILITY_TRANSITION_STEPS 500U
#define REACHY_STABILITY_HOLD_STEPS 500U
#define REACHY_STABILITY_STEPS_PER_PHASE UINT64_C(1000)
#define REACHY_STABILITY_STEPS_PER_CYCLE UINT64_C(20000)
#define REACHY_STABILITY_REQUIRED_ANDROID_CYCLES 45U

typedef struct ReachyStabilityPhase {
    const char* name;
    const char* category;
    double targets[REACHY_STABILITY_ACTUATOR_COUNT];
    uint32_t allowed_out_of_range_mask;
} ReachyStabilityPhase;

static const char REACHY_STABILITY_PROFILE_ID[] = "upstream_baseline";
static const char REACHY_STABILITY_PROFILE_SHA256[] = "c1e9564cac6e967a6ee726c42a9d2882acf7d473d4302cbf808e20f92cddfecd";
static const char REACHY_STABILITY_MODEL_SHA256[] = "efd7e49d4288e5ef53945771a1f116584aa2c8b89721b725d5d77da9f0fcbf46";
static const char REACHY_STABILITY_MUJOCO_VERSION[] = "3.9.0";
static const char REACHY_STABILITY_UPSTREAM_COMMIT[] = "a739a6e461eb6d722901f1cfc225265ffc85c28d";
static const double REACHY_STABILITY_TIMESTEP_SECONDS = 0.002;
static const double REACHY_STABILITY_REQUIRED_SIMULATED_SECONDS = 1800;
static const double REACHY_STABILITY_MINIMUM_SOLVER_REALTIME_FACTOR = 1;
static const double REACHY_STABILITY_MAXIMUM_EQUALITY_RESIDUAL = 0.001;
static const double REACHY_STABILITY_MAXIMUM_JOINT_LIMIT_VIOLATION = 9.9999999999999995e-07;
static const double REACHY_STABILITY_MAXIMUM_CONTACT_PENETRATION = 0.01;
static const double REACHY_STABILITY_MAXIMUM_ABSOLUTE_TOTAL_ENERGY = 100;

static const char* const REACHY_STABILITY_ACTUATOR_NAMES[REACHY_STABILITY_ACTUATOR_COUNT] = {
    "yaw_body",
    "stewart_1",
    "stewart_2",
    "stewart_3",
    "stewart_4",
    "stewart_5",
    "stewart_6",
    "right_antenna",
    "left_antenna",
};

static const ReachyStabilityPhase REACHY_STABILITY_PHASES[REACHY_STABILITY_PHASE_COUNT] = {
    {"neutral_awake", "neutral", {0, 0, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"upstream_sleep_request", "sleep", {0, -0.98481566582258173, 1.2624661884298831, -0.24390294527381684, 0.20555342557667577, -1.2363885150358267, 1.0032234352772091, -3.0499999999999998, 3.0499999999999998}, UINT32_C(102)},
    {"neutral_after_sleep", "neutral", {0, 0, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"body_yaw_positive_limit", "body_yaw_limit", {2.7925268031908792, 0, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"body_yaw_negative_limit", "body_yaw_limit", {-2.7925268031909751, 0, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_1_negative_limit", "head_actuator_limit", {0, -0.83775804095721962, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_1_positive_limit", "head_actuator_limit", {0, 1.3962634015955222, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_2_negative_limit", "head_actuator_limit", {0, 0, -1.3962634015956139, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_2_positive_limit", "head_actuator_limit", {0, 0, 1.2217304763958803, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_3_negative_limit", "head_actuator_limit", {0, 0, 0, -0.83775804095721729, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_3_positive_limit", "head_actuator_limit", {0, 0, 0, 1.3962634015955244, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_4_negative_limit", "head_actuator_limit", {0, 0, 0, 0, -1.3962634015953894, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_4_positive_limit", "head_actuator_limit", {0, 0, 0, 0, 0.83775804095735251, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_5_negative_limit", "head_actuator_limit", {0, 0, 0, 0, 0, -1.2217304763962082, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_5_positive_limit", "head_actuator_limit", {0, 0, 0, 0, 0, 1.3962634015952859, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_6_negative_limit", "head_actuator_limit", {0, 0, 0, 0, 0, 0, -1.3962634015954123, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"head_motor_6_positive_limit", "head_actuator_limit", {0, 0, 0, 0, 0, 0, 0.83775804095732964, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
    {"antennas_sleep_extreme", "antenna_extreme", {0, 0, 0, 0, 0, 0, 0, -3.0499999999999998, 3.0499999999999998}, UINT32_C(0)},
    {"antennas_mirrored_extreme", "antenna_extreme", {0, 0, 0, 0, 0, 0, 0, 3.0499999999999998, -3.0499999999999998}, UINT32_C(0)},
    {"neutral_final", "neutral", {0, 0, 0, 0, 0, 0, 0, -0.17449999999999999, 0.17449999999999999}, UINT32_C(0)},
};

static const uint32_t REACHY_STABILITY_EXPECTED_BODY_COUNT = 19U;
static const uint32_t REACHY_STABILITY_EXPECTED_JOINT_COUNT = 16U;
static const uint32_t REACHY_STABILITY_EXPECTED_ACTUATOR_COUNT = 9U;
static const uint32_t REACHY_STABILITY_EXPECTED_EQUALITY_COUNT = 5U;
static const uint32_t REACHY_STABILITY_EXPECTED_NQ = 37U;
static const uint32_t REACHY_STABILITY_EXPECTED_NV = 30U;

#endif
