apply plugin: 'com.android.library'

def cameraxVersion = '1.6.1'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.camera:camera-core:${cameraxVersion}"
    implementation "androidx.camera:camera-camera2:${cameraxVersion}"
    implementation "androidx.camera:camera-lifecycle:${cameraxVersion}"
    implementation 'com.google.mlkit:face-detection:16.1.7'
    implementation 'com.google.mlkit:segmentation-selfie:16.0.0-beta6'
}

android {
    namespace "com.ekkus93.weachy.camera"
    compileSdk getProperty("unity.compileSdkVersion") as int
    buildToolsVersion = getProperty("unity.buildToolsVersion")

    compileOptions {
        sourceCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion"))
        targetCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion"))
    }

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int
        versionCode getProperty("unity.versionCode") as int
        versionName getProperty("unity.versionName")
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}
