#!/usr/bin/env python3
"""One-shot RMA-072 TODO evidence finalization."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
todo_path = ROOT / "docs/REACHY_MINI_ANDROID_DIGITAL_TWIN_TODO.md"
todo = todo_path.read_text(encoding="utf-8")
old = '## RMA-072 — Implement experiment runner\n\n- [ ] Implement scripted unloaded sweeps.\n- [ ] Implement gravity-loaded static-pose tests.\n- [ ] Implement step and frequency-response tests.\n- [ ] Implement backlash direction-reversal tests.\n- [ ] Implement torque-disabled/free-decay tests.\n- [ ] Implement multi-actuator and warm/cold tests.\n- [ ] Add safety notes for physical test execution.\n'
new = '## RMA-072 — Implement experiment runner\n\n**Status:** Complete (2026-07-31)\n\n- [x] Implement scripted unloaded sweeps.\n- [x] Implement gravity-loaded static-pose tests.\n- [x] Implement step and frequency-response tests.\n- [x] Implement backlash direction-reversal tests.\n- [x] Implement torque-disabled/free-decay tests.\n- [x] Implement multi-actuator and warm/cold tests.\n- [x] Add safety notes for physical test execution.\n\n**Completion evidence**\n\n- `rma072_calibration_experiment_plan_v1` defines a versioned, canonical-hash\n  bound plan for robot identity, monotonic timing, actuator soft/profile\n  limits, resource ceilings, live electrical/thermal abort limits, and ordered\n  experiments.\n- The deterministic compiler covers unloaded sweeps, gravity-loaded static\n  poses, step response, sinusoidal frequency response, backlash reversals,\n  torque-disabled free decay, simultaneous multi-actuator commands, and\n  warm/cold thermal cycles. The committed synthetic smoke plan compiles to 347\n  actions over 23.4 seconds with schedule SHA-256\n  `96fa8b8131765b0f1d7c3ef61ba95c8038c5ee6cf52fcfd615902df776bfdcfd`.\n- Dry-run output includes a versioned manifest, the complete action schedule,\n  and RMA-070-shaped command JSONL. The permanent gate imported 312 generated\n  command samples through the RMA-071 capture tool and validated dataset\n  SHA-256\n  `138652fd99c1ccc54e081c6fca81260cf09681f35d4f144617751aaa5bdc035b`.\n- Physical execution remains behind the `ExperimentAdapter` boundary. Exact\n  plan hash, robot identity, operator presence, workspace clearance,\n  emergency-stop verification, acknowledgement, and explicit motion\n  authorization are required before startup. Voltage, current, temperature,\n  emergency-stop availability, and robot fault state are checked before every\n  action; any violation or adapter exception invokes emergency stop and\n  records an aborted run.\n- The schedule explicitly disables torque for free-decay release and for every\n  used actuator during final safe shutdown. The CLI has no generic physical\n  motion switch.\n- Permanent workflow run `30667664533` passed Python compilation, all 39\n  calibration regression tests, all eight experiment families, the dry-run\n  CLI, the RMA-070/RMA-071 bridge, and evidence hashing on exact implementation\n  commit `de8b95eee5ffdae90c9409fa49887d3d603d6913`.\n- Artifact `8807575014`,\n  `rma072-experiment-runner-evidence-de8b95eee5ffdae90c9409fa49887d3d603d6913`,\n  has ZIP SHA-256\n  `be4aaea8262b240d10a57f6c75f63666a83eac5202c352657a60c921f2a9bb06`.\n- The committed fixture and automated execution are synthetic orchestration\n  evidence only. A production Reachy adapter and physical unit data remain\n  RMA-074 work.\n- Detailed design, safety, and evidence are in\n  `docs/architecture/CALIBRATION_EXPERIMENT_RUNNER.md`,\n  `docs/operations/CALIBRATION_EXPERIMENT_SAFETY.md`, and\n  `docs/validation/RMA_072_EXPERIMENT_RUNNER_VALIDATION_2026-07-31.md`.\n'
if todo.count(old) != 1:
    raise RuntimeError(f"expected exactly one RMA-072 TODO block, found {todo.count(old)}")
todo_path.write_text(todo.replace(old, new), encoding="utf-8", newline="\n")
print("RMA-072 TODO evidence finalized")
