apply plugin: 'com.android.library'

dependencies {
    compileOnly 'androidx.annotation:annotation:1.10.0'
}

android {
    namespace "com.ekkus93.weachy.speech"
    compileSdk getProperty("unity.compileSdkVersion") as int
    buildToolsVersion = getProperty("unity.buildToolsVersion")

    compileOptions {
        sourceCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion"))
        targetCompatibility JavaVersion.valueOf(
            getProperty("unity.javaCompatabilityVersion"))
    }

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int
        versionCode getProperty("unity.versionCode") as int
        versionName getProperty("unity.versionName")
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}
